version: '3.9'

services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    container_name: mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    env_file:
      - .env
    volumes:
      - .:/app
      - ../dvc_remote:/app/../dvc_remote
    container_name: api_server

  inference:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - fastapi
    entrypoint: ["python", "inference.py"]
    container_name: inference_runner

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - fastapi
    volumes:
      - .:/app
      - ../dvc_remote:/app/../dvc_remote
    container_name: test-client
    restart: on-failure
